name: Agente NTs - Execução + E-mail

on:
  schedule:
    # Terça e Sexta às 12:00 UTC (ajuste se quiser outro horário)
    - cron: "0 12 * * 2,5"
  workflow_dispatch:

jobs:
  run-and-notify:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Instalar dependências
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

      - name: Rodar agente (gerar resultado_nts.xlsx)
        id: agente
        env:
          PYTHONUNBUFFERED: "1"
        run: |
          python -m agente_nts.main || exit 1
          echo "RESULT_FILE=output/resultado_nts.xlsx" >> $GITHUB_ENV
          if [ -f "output/resultado_nts.xlsx" ]; then
            echo "Arquivo de resultado gerado."
          else
            echo "Arquivo de resultado NÃO encontrado."
          fi

      - name: Publicar artifact (resultado_nts.xlsx) se existir
        if: ${{ hashFiles('output/resultado_nts.xlsx') != '' }}
        uses: actions/upload-artifact@v4
        with:
          name: resultado_nts
          path: output/resultado_nts.xlsx
          retention-days: 14

      - name: Enviar e-mail de notificação
        if: always()   # manda mesmo se der falha; troque para success() se quiser só em sucesso
        uses: dawidd6/action-send-mail@v3
        with:
          server_address: ${{ secrets.MAIL_SERVER }}
          server_port: ${{ secrets.MAIL_PORT }}
          username: ${{ secrets.MAIL_USERNAME }}
          password: ${{ secrets.MAIL_PASSWORD }}
          subject: "Agente NTs: execução em ${{ github.repository }} (#${{ github.run_number }})"
          to: ${{ secrets.MAIL_TO }}
          from: ${{ secrets.MAIL_FROM }}
          secure: true
          convert_markdown: true
          # Se quiser anexar o arquivo quando existir:
          attachments: |
            output/resultado_nts.xlsx
          body: |
            ## ✅ Agente NTs executado

            - **Repositório:** ${{ github.repository }}
            - **Branch:** `${{ github.ref_name }}`
            - **Run ID:** ${{ github.run_id }}
            - **Status do job:** ${{ job.status }}
            - **Data (UTC):** ${{ steps.agente.outputs.time || '' }}

            **Página do run:** https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}

            ${{
              hashFiles('output/resultado_nts.xlsx') != '' &&
              'O arquivo *output/resultado_nts.xlsx* foi gerado e está anexado nesta mensagem (se o provedor permitir anexos). Também fica disponível em **Artifacts** na página do run.'
            }}
