name: Rodar agente (gerar resultado_nts.xlsx)

on:
  workflow_dispatch:
  schedule:
    # 2x por semana: seg e qui às 12:00 UTC
    - cron: '0 12 * * 1,4'

jobs:
  run:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Instalar dependências
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
          if [ -f agente_nts/requirements.txt ]; then pip install -r agente_nts/requirements.txt; fi
          # garante libs críticas mesmo sem requirements
          pip install "pypdf>=4.2" "pdfplumber>=0.11" "beautifulsoup4>=4.12" "lxml>=5.0" "pandas>=2.2" "openpyxl>=3.1" "python-dotenv>=1.0"

      - name: Rodar agente
        run: python -m agente_nts.main

      - name: Publicar artifact (resultado_nts.xlsx)
        uses: actions/upload-artifact@v4
        with:
          name: resultado_nts
          path: output/resultado_nts.xlsx
          if-no-files-found: warn
