name: Agente NTs - Extração Semanal

on:
  schedule:
    - cron: "0 12 * * 1"
  workflow_dispatch:

permissions:
  contents: write

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run agent
        run: python -m src.main

      - name: Upload artifact (resultado_nts.xlsx)
        uses: actions/upload-artifact@v4
        with:
          name: resultado_nts
          path: output/resultado_nts.xlsx

      - name: Commit results back to repo (optional)
        if: ${{ vars.PUSH_RESULTS == 'true' }}
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add output/resultado_nts.xlsx
          git commit -m "chore: update resultado_nts.xlsx [ci skip]" || echo "No changes to commit"
          git push
